server:
  port: 8701 #服务端口
#spring相关配置
spring:
  application:
    name: consumer-payment  #服务名
  datasource:
    url: jdbc:mysql://localhost:3306/myblog?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false

#eureka配置
eureka:
  client:
    #表示是否将自己注册进eureka  默认为true
    register-with-eureka: true
    #是否从EurekaServer中抓取已有的注册信息，默认为true，单点无所谓，集群必须设置true才能和ribbon使用负载均衡
    fetch-registry: true
    service-url:
      #单机配置
      defaultZone: http://eureka-server8902.com:8902/eureka,http://eureka-server8901.com:8901/eureka