server:
  port: 8702
spring:
  application:
    name: consul-consumer-order
  cloud:
    consul:
      # consul注册地址
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}